### ISSUE TITLE
Is this project unmaintained?

### ISSUE THREAD

**Issue by brejoc** [fireteam/virtualenv-tools#11]
I'm under the impression, that the project is no longer maintained. There are quite a few open pull requests and Python3 support seems to be missing. I've also noticed some forks with changes and additions that could be handy.

Are there any plans for the future? Thanks!

**Comment by asottile** [comment]
[We](https://github.com/Yelp/virtualenv-tools)'d be willing to either help maintain this project or take over the pypi name.  Our fork has added test coverage, a few bug fixes, pth file support, and python 3 support.

**Comment by chriskuehl** [comment]
Yelp has published its fork (which has the patches @asottile mentioned above) as `virtualenv-tools3`. We'd still be happy to help maintain this project or take over the PyPI name if anyone at @fireteam is interested :)

https://github.com/Yelp/virtualenv-tools
https://pypi.python.org/pypi/virtualenv-tools3

**Comment by brejoc** [comment]
Cleaning up. If you think this should be re-opened, feel free to do so or contact me.
